version: 0.2
env:
  variables:
    ECR_REPO: 239325463569.dkr.ecr.us-west-2.amazonaws.com/demo/myapp
phases:
  install:
    runtime-versions:
      java: corretto25
    commands:
      # Start Docker daemon if not already running (required for privileged builds)
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  build:
    commands:
      - java -version
      - mvn clean package
      - echo "Building a Docker image.."
      - docker build -t ${ECR_REPO}:${CODEBUILD_SOURCE_VERSION} .
